#!/bin/bash -x

OCAMLCFLAGS="-c -bin-annot -safe-string -package ctypes.stubs -package bigarray -package bytes -w @5@8@10@11@12@14@23@24@26@29 -I lib_gen -I lib"
OCAMLC="ocamlfind ocamlc $(OCAMLCFLAGS)"
OCAMLOPT="ocamlfind ocamlopt $(OCAMLCFLAGS)"

$(OCAMLC) -o lib_gen/sodium_types.cmo lib_gen/sodium_types.ml
$(OCAMLC) -o lib_gen/sodium_typegen.cmo lib_gen/sodium_typegen.ml
ocamlfind ocamlc -linkpkg -package ctypes.stubs lib_gen/sodium_types.cmo lib_gen/sodium_typegen.cmo -o lib_gen/sodium_typegen.byte
lib_gen/sodium_typegen.byte
cc -I /home/chet/Hack/ocaml-4.02.3/.opam/system/lib/ctypes -I /home/chet/Hack/ocaml-4.02.3/lib/ocaml -o lib_gen/sodium_types_detect lib_gen/sodium_types_detect.c
lib_gen/sodium_types_detect > lib/sodium_types_detected.ml
$(OCAMLC) -o lib/sodium_storage.cmo lib/sodium_storage.ml
$(OCAMLC) -o lib/sodium_types_detected.cmo lib/sodium_types_detected.ml
$(OCAMLC) -o lib_gen/sodium_bindings.cmo lib_gen/sodium_bindings.ml
$(OCAMLC) -o lib_gen/sodium_bindgen.cmo lib_gen/sodium_bindgen.ml
ocamlfind ocamlc -linkpkg -package ctypes.stubs lib/sodium_storage.cmo lib/sodium_types_detected.cmo lib_gen/sodium_types.cmo lib_gen/sodium_bindings.cmo lib_gen/sodium_bindgen.cmo -o lib_gen/sodium_bindgen.byte
lib_gen/sodium_bindgen.byte
ocamlfind ocamlc -ccopt -I/usr/local/include -I /home/chet/Hack/ocaml-4.02.3/.opam/system/lib/ctypes -ccopt '--std=c99 -Wall -pedantic -Werror -Wno-pointer-sign' -c lib/sodium_stubs.c
mv sodium_stubs.o lib/sodium_stubs.o
ocamlfind ocamlmklib -o lib/sodium_stubs -L/usr/local/lib -lsodium lib/sodium_stubs.o
$(OCAMLC) -o lib/sodium.cmi lib/sodium.mli
cp -p lib_gen/sodium_bindings.ml lib/sodium_bindings.ml
cp -p lib_gen/sodium_types.ml lib/sodium_types.ml
$(OCAMLC) -o lib/sodium_types.cmo lib/sodium_types.ml
$(OCAMLC) -o lib/sodium_bindings.cmo lib/sodium_bindings.ml
$(OCAMLC) -o lib/sodium_generated.cmo lib/sodium_generated.ml
$(OCAMLC) -o lib/sodium.cmo lib/sodium.ml
ocamlfind ocamlc -a -dllib -lsodium_stubs lib/sodium_storage.cmo lib/sodium_types.cmo lib/sodium_types_detected.cmo lib/sodium_bindings.cmo lib/sodium_generated.cmo lib/sodium.cmo -o lib/sodium.cma
$(OCAMLOPT) -o lib/sodium_storage.cmx lib/sodium_storage.ml
$(OCAMLOPT) -o lib/sodium_types.cmx lib/sodium_types.ml
$(OCAMLOPT) -o lib/sodium_types_detected.cmx lib/sodium_types_detected.ml
$(OCAMLOPT) -o lib/sodium_bindings.cmx lib/sodium_bindings.ml
$(OCAMLOPT) -o lib/sodium_generated.cmx lib/sodium_generated.ml
$(OCAMLOPT) -o lib/sodium.cmx lib/sodium.ml
ocamlfind ocamlopt -a -cclib -lsodium_stubs -cclib -lsodium lib/sodium_storage.cmx lib/sodium_types.cmx lib/sodium_types_detected.cmx lib/sodium_bindings.cmx lib/sodium_generated.cmx lib/sodium.cmx -o lib/sodium.cmxa
